#!/data/data/com.termux/files/usr/bin/python3
import argparse
import hashlib
import json
import pathlib
import re
import sys

OPS = ("FS", "FMS", "CSFLT", "CFLTS")
PREFIX = "GAMEDECK_SPU_LLVM_PROVENANCE_V1"


def function_body(text: str, op: str) -> str:
    match = re.search(rf"\bvoid\s+{op}\(spu_opcode_t op\)", text)
    if not match:
        raise SystemExit(f"missing LLVM opcode body: {op}")
    start = text.find("{", match.end())
    if start < 0:
        raise SystemExit(f"missing opening brace for LLVM opcode body: {op}")
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[match.start():i + 1]
    raise SystemExit(f"unclosed LLVM opcode body: {op}")


def provenance(source: pathlib.Path):
    raw = source.read_bytes()
    text = raw.decode("utf-8")
    bodies = {
        op: hashlib.sha256(function_body(text, op).encode("utf-8")).hexdigest()
        for op in OPS
    }
    source_sha = hashlib.sha256(raw).hexdigest()
    manifest = PREFIX + "|source_sha256=" + source_sha
    for op in OPS:
        manifest += f"|{op}={bodies[op]}"
    return source_sha, bodies, manifest


def emit_cpp(path: pathlib.Path, manifest: str):
    body = f'''// Generated by mobile/android/tools/spu-llvm-provenance.py.
// Do not hand-edit. Regenerate before rebuilding libe.so.
extern "C" {{
__attribute__((used, retain, visibility("default"), section(".rodata.gamedeck_spu_llvm_provenance")))
extern const char gamedeck_spu_llvm_provenance[] =
    "{manifest}";
}}
'''
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=pathlib.Path)
    parser.add_argument("--emit-cpp", type=pathlib.Path)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--verify-binary", type=pathlib.Path)
    group.add_argument("--verify-object", type=pathlib.Path)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    source_sha, bodies, manifest = provenance(args.source)

    if args.emit_cpp:
        emit_cpp(args.emit_cpp, manifest)

    verified = None
    artifact_kind = None
    artifact = args.verify_binary or args.verify_object
    if artifact:
        artifact_kind = "binary" if args.verify_binary else "object"
        data = artifact.read_bytes()
        verified = manifest.encode("ascii") in data
        if not verified:
            label = artifact_kind.upper()
            print(f"SPU_LLVM_{label}_PROVENANCE_FAIL embedded manifest mismatch", file=sys.stderr)
            return 2

    if args.json:
        print(json.dumps({
            "schema": 1,
            "source_sha256": source_sha,
            "body_sha256": bodies,
            "manifest": manifest,
            "artifact_kind": artifact_kind,
            "artifact_verified": verified,
            "binary_verified": verified if artifact_kind == "binary" else None,
            "object_verified": verified if artifact_kind == "object" else None,
        }, indent=2, sort_keys=True))
    else:
        print(manifest)
        if verified:
            if artifact_kind == "binary":
                print("SPU_LLVM_BINARY_PROVENANCE_PASS source_and_binary_manifest_match")
            else:
                print("SPU_LLVM_OBJECT_PROVENANCE_PASS source_and_object_manifest_match")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
