// Generated by mobile/android/tools/spu-llvm-provenance.py.
// Do not hand-edit. Regenerate before rebuilding libe.so.
extern "C" {
__attribute__((used, retain, visibility("default"), section(".rodata.gamedeck_spu_llvm_provenance")))
extern const char gamedeck_spu_llvm_provenance[] =
    "GAMEDECK_SPU_LLVM_PROVENANCE_V1|source_sha256=27e5a39f64b0afb99f87027d37d988b9dab8661eafd22911ba8282751a81b1f0|FS=2dbaa0fec663ec61b7ba72a8e3c6df62fcb7d0954f9c7490023b7ad26322ede5|FMS=fe4aa3615dca700270b5d1a43a70d01e1e928b01d93759178df2858c013dafde|CSFLT=c7469ea1926b70a4832ca09c82e115d58e78a2edcab66f8849fbedf636c08907|CFLTS=729b99b1b55d6d4fc53ac8e332bf20203b5f5b31fbc3f6cf76e586a6344247d5";
}
